version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clean_like
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: "postgres://root:password@db/clean_like?sslmode=disable"
    depends_on:
      - db
  backend:
    image: go-clean
    build: ./
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://root:password@db/clean_like?sslmode=disable"
    volumes:
      - .:/go/src/go-clean
    command: ["fresh", "-c", "runner.conf"]
    depends_on:
      - db
volumes:
  postgres_data:
